/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CozinhaRouteImport } from './routes/cozinha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PedidosRouteImport } from './routes/pedidos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CozinhaRoute = CozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cozinha': typeof CozinhaRoute
  '/entrar': typeof EntrarRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cozinha': typeof CozinhaRoute
  '/entrar': typeof EntrarRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cozinha': typeof CozinhaRoute
  '/entrar': typeof EntrarRoute
  '/pedidos': typeof PedidosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cozinha' | '/entrar' | '/pedidos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cozinha' | '/entrar' | '/pedidos'
  id: '__root__' | '/' | '/cozinha' | '/entrar' | '/pedidos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CozinhaRoute: typeof CozinhaRoute
  EntrarRoute: typeof EntrarRoute
  PedidosRoute: typeof PedidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cozinha': {
      id: '/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof CozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CozinhaRoute: CozinhaRoute,
  EntrarRoute: EntrarRoute,
  PedidosRoute: PedidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
